name: Java CI

on:
  pull_request:
    branches:
      - master
      - dev

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Installing XVFB
      run: sudo apt-get install xvfb
    - name: Test with Gradle
      run: xvfb-run ./gradlew test --info

  code_quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: run style check on main source sets
        run: ./gradlew checkstyleMain --info
      - name: run style check on test source sets
          run: ./gradlew checkstyleTest --info

