/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sample;

import javafx.application.Application;
import javafx.stage.Stage;


import javafx.application.Application;
import javafx.stage.Stage;

public class App extends Application {
    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) {
        primaryStage.setTitle("Hello World!");
        primaryStage.show();
    }
}
